baseURL: "https://octavemariotti.github.io/" 
title: Octave Mariotti
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

# menu:
#     main:
#         - name: Books
#           url: books/
#           weight: 5 
#         - name: Papers
#           url: papers/
#           weight: 2
#         - name: Courses
#           url: courses/
#           weight: 3
#         - name: Data
#           url: data/
#           weight: 4 
#         - name: Blog
#           url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#           weight: 6


params:
    description: "I am a post-doctoral researcher in Computer Vision and Machine Leraning"
    author: Octave Mariotti
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Octave Mariotti
          subtitle: "I am a post-doctoral researcher in Computer Vision and Machine Leraning at the 
          [School of Informatics](https://informatics.ed.ac.uk/) of the University of Edinburgh. 
          I am part of the [Visual Computing Group](https://groups.inf.ed.ac.uk/vico) and the
          [Visual AI project](https://www.robots.ox.ac.uk/~vgg/projects/visualai/index.html), 
          working principally with [Hakan Bilen](https://homepages.inf.ed.ac.uk/hbilen/) and 
          [Oisin Mac Aodha](https://homepages.inf.ed.ac.uk/omacaod/).\n

          My research interests cover learning without human annotations, 3D awareness in deep
          image models and robustness in evaluation.\n

          I completed my PhD in 2022 at the University of Edinburgh under the supervision of Hakan Bilen.
          Before that, I obtained a Bachelor and Master degrees in theoretical computer science from the 
          [ENS de Lyon](https://www.ens-lyon.fr/en/).\n

          ---

          Email: omariott (at) ed.ac.uk

          "
          imageUrl: "picture.jpeg"
          imageWidth: 256
          imageHeight: 256
          imageTitle: Octave Mariotti

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kaGm6fcAAAAJ
        - name: GitHub
          url: https://github.com/omariott

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Octave Mariotti"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2